Parser + Tokenizer
WispLang/Wisp pull request #1
Opened 2022-08-31 10:44 UTC by ENDERZOMBI102

In this PR i've worked on the parser and the tokenizer to make them work and output somewhat decent error messages

2022-08-31 12:05 UTC, Oliver-makes-code requested changes
A couple changes, otherwise lgtm

2022-08-31 12:05 UTC, Oliver-makes-code commented on src/main/kotlin/dev/wisplang/wisp/ast/Type.kt
> +                if (type.name.lowercase() == name)
Primitives shouldn't be case insensitive

2022-08-31 12:05 UTC, Oliver-makes-code commented on src/main/kotlin/dev/wisplang/wisp/ast/Type.kt
> +    U64, I64, F64;
Formatting is a little weird

2022-08-31 12:05 UTC, Oliver-makes-code commented on src/main/kotlin/dev/wisplang/wisp/tokenizer/Keywords.kt
> +        fun strings() = STRINGS
This isn't kotlin convention, you could make STRINGS public and just access that

2022-08-31 15:49 UTC, ENDERZOMBI102 commented on src/main/kotlin/dev/wisplang/wisp/ast/Type.kt
> +                if (type.name.lowercase() == name)
they... are not case insensitive?
read the code, i'm lowercasing the enum names, not the parameter

2022-08-31 15:50 UTC, ENDERZOMBI102 commented on src/main/kotlin/dev/wisplang/wisp/ast/Type.kt
> +    U64, I64, F64;
reformatted

2022-08-31 15:50 UTC, ENDERZOMBI102 commented on src/main/kotlin/dev/wisplang/wisp/tokenizer/Keywords.kt
> +        fun strings() = STRINGS
k

2022-08-31 21:24 UTC, Oliver-makes-code approved these changes
Looks good

2022-08-31 23:56 UTC, TibiNonEst approved these changes
LGTM

2022-09-01 17:38 UTC, ENDERZOMBI102 commented
welp me mrg

2022-09-01 17:39 UTC, merged